# Generated by Django 4.1.7 on 2023-05-09 07:31

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0002_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True, verbose_name='create_at')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='update_at')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('description', models.TextField(null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='is active')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='create_by')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_page', to='organisation.group')),
                ('update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='update_by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='geometry')),
                ('info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geoObject_info', to='organisation.geoinfo')),
            ],
            options={
                'verbose_name': 'geoObject',
                'verbose_name_plural': 'geoObjects',
                'ordering': ('info__group',),
            },
        ),
    ]
