# Generated by Django 4.1.7 on 2023-05-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_geoinfo_geoobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
